
---
apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    comment: ""
    documentation: https://traveltrex.atlassian.net/wiki/spaces/ITSoftware/pages/28030737/Kundenumfrage+-+Entwicklerdokumentation
    forceCompleteRequest: 2026-01-07T13:36:54.746+01:00
    image: registry.k8s.traveltrex.local/schedtask-powershell
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"batch/v1","kind":"CronJob","metadata":{"annotations":{"comment":"","documentation":"https://traveltrex.atlassian.net/wiki/spaces/ITSoftware/pages/28030737/Kundenumfrage+-+Entwicklerdokumentation","forceCompleteRequest":"2024-09-19T16:17:07.306+02:00","image":"registry.k8s.traveltrex.local/schedtask-powershell","lastchangeoperation":"Edit","lastchangetime":"2023-08-25T13:13:03.323+02:00","lastchangeuser":"Vitali Müller","logging":"http://logstash-intern:9292/index.html#/dashboard/elasticsearch/Kundenumfrage","nagiosLabels":"TEAMMYTREX","tag":"1.0.17","template":"schedtask-powershell"},"labels":{"argocd.argoproj.io/instance":"kubertasks-cronjobs","groupName":"Kundenumfrage-Configuration"},"name":"kundenumfrage-configuration-xyjvi-a4d26","namespace":"scheduledtask"},"spec":{"concurrencyPolicy":"Forbid","failedJobsHistoryLimit":1,"jobTemplate":{"metadata":{"creationTimestamp":null,"labels":{"groupName":"Kundenumfrage-Configuration"}},"spec":{"activeDeadlineSeconds":120,"backoffLimit":0,"template":{"metadata":{"creationTimestamp":null,"labels":{"groupName":"Kundenumfrage-Configuration"}},"spec":{"containers":[{"env":[{"name":"SCRIPT","value":"InvokeWebApiAction.ps1 http://kundenumfrage.iis10-live.traveltrex.local/api/import/configuration"},{"name":"DIRECTORY","value":"InvokeWebApiAction"}],"image":"registry.k8s.traveltrex.local/schedtask-powershell:1.0.17","imagePullPolicy":"IfNotPresent","name":"powershell","resources":{"limits":{"cpu":"50m","memory":"50Mi"},"requests":{"cpu":"50m","memory":"50Mi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/mnt/scheduledtask","name":"scheduledtask"},{"mountPath":"/mnt/dx01/AppShare","name":"dx01"}]}],"dnsPolicy":"ClusterFirst","nodeSelector":{"kubernetes.io/os":"linux"},"restartPolicy":"Never","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"name":"scheduledtask","persistentVolumeClaim":{"claimName":"pvc-taskplaner-tools"}},{"name":"dx01","persistentVolumeClaim":{"claimName":"pvc-dx01-appshare"}}]}}}},"schedule":"13 * * * *","startingDeadlineSeconds":21600,"successfulJobsHistoryLimit":1,"suspend":false,"timeZone":"Europe/Berlin"}}
    lastchangeoperation: Edit
    lastchangetime: 2025-08-05T13:37:13.258+02:00
    lastchangeuser: Vitali Müller
    logging: http://logstash-intern:9292/index.html#/dashboard/elasticsearch/Kundenumfrage
    nagiosLabels: TEAMMYTREX
    tag: 1.0.17
    template: schedtask-powershell
    environment: live
  labels:
    argocd.argoproj.io/instance: kubertasks-cronjobs
    groupName: Kundenumfrage-Configuration
  name: kundenumfrage-configuration-xyjvi-a4d26
  namespace: scheduledtask-test
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        groupName: Kundenumfrage-Configuration
    spec:
      activeDeadlineSeconds: 120
      backoffLimit: 0
      template:
        metadata:
          labels:
            groupName: Kundenumfrage-Configuration
        spec:
          containers:
          - env:
            - name: SCRIPT
              value: InvokeWebApiAction.ps1 http://kundenumfrage.iis10-live.traveltrex.local/api/import/configuration
            - name: DIRECTORY
              value: InvokeWebApiAction
            image: registry.k8s.traveltrex.local/schedtask-powershell:1.0.17
            imagePullPolicy: IfNotPresent
            name: powershell
            resources:
              limits:
                cpu: 50m
                memory: 50Mi
              requests:
                cpu: 50m
                memory: 50Mi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /mnt/scheduledtask
              name: scheduledtask
            - mountPath: /mnt/dx01/AppShare
              name: dx01
          dnsPolicy: ClusterFirst
          nodeSelector:
            kubernetes.io/os: linux
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - name: scheduledtask
            persistentVolumeClaim:
              claimName: pvc-taskplaner-tools
          - name: dx01
            persistentVolumeClaim:
              claimName: pvc-dx01-appshare
  schedule: 13 * * * *
  startingDeadlineSeconds: 21600
  successfulJobsHistoryLimit: 1
  suspend: true
  timeZone: Europe/Berlin